Feature/manu/delete book
manu-neufeld/punto-y-leido-front pull request #13
Opened 2020-12-05 18:46 UTC by manu-neufeld

He creado una nueva rama, en la anterior borré componentes que no permiten hacer merge con main. Dejo la anterior rama hasta que se acepte esta pull request, se haga el merge y comprobemos que todo funciona.

2020-12-09 10:57 UTC, JimenaEB commented
Esta también estaba corregida no?

2020-12-10 11:43 UTC, JuanLGC requested changes

2020-12-10 11:43 UTC, JuanLGC commented on src/styles/littleBookCover.scss
> +    // display: flex;
comentarios se borran si no se usan

2020-12-10 11:43 UTC, JuanLGC commented on src/styles/littleBookCover.scss
> +    .boton{
una clase en ingles, otra en spanish

2020-12-10 11:44 UTC, JuanLGC approved these changes

2020-12-10 15:01 UTC, closed without merging